/**
 * Demo/static seed data — used by the seed script AND fallback when no DB is available.
 *
 * When deployed on Vercel without a database, API routes return this data directly.
 */

export interface DemoMemory {
  title: string;
  place: string;
  date: string;
  year: string;
  lat: number;
  lng: number;
  color: string;
  kind: string;
  image: string | null;
  media: string[];
  favorite: boolean;
  description: string | null;
  note: string | null;
  symbol: string;
  city: string | null;
  country: string | null;
  tags: string[];
}

export const DEMO_MEMORIES: DemoMemory[] = [
  {
    title: "Shibuya crossing at midnight",
    place: "Shibuya, Tokyo",
    date: "2026-03-15",
    year: "2026",
    lat: 35.6595,
    lng: 139.7004,
    color: "#ef766b",
    kind: "memory",
    image: "https://picsum.photos/seed/tokyo-shibuya/800/600",
    media: [
      "https://picsum.photos/seed/tokyo-1/800/600",
      "https://picsum.photos/seed/tokyo-2/800/600",
    ],
    favorite: true,
    description: "A memory from Tokyo, Japan.",
    note: null,
    symbol: "star",
    city: "Tokyo",
    country: "Japan",
    tags: ["city", "night", "travel"],
  },
  {
    title: "Sunrise over the temples",
    place: "Bagan",
    date: "2026-02-10",
    year: "2026",
    lat: 21.1722,
    lng: 94.86,
    color: "#f4a261",
    kind: "memory",
    image: "https://picsum.photos/seed/bagan-sunrise/800/600",
    media: [
      "https://picsum.photos/seed/bagan-1/800/600",
      "https://picsum.photos/seed/bagan-2/800/600",
      "https://picsum.photos/seed/bagan-3/800/600",
    ],
    favorite: false,
    description: "A memory from Bagan, Myanmar.",
    note: null,
    symbol: "pin",
    city: "Bagan",
    country: "Myanmar",
    tags: ["nature", "sunrise", "travel"],
  },
  {
    title: "Lost in the medina",
    place: "Marrakech",
    date: "2025-11-20",
    year: "2025",
    lat: 31.6295,
    lng: -7.9811,
    color: "#e76f51",
    kind: "memory",
    image: "https://picsum.photos/seed/marrakech-medina/800/600",
    media: ["https://picsum.photos/seed/marrakech-1/800/600"],
    favorite: false,
    description: "A memory from Marrakech, Morocco.",
    note: null,
    symbol: "pin",
    city: "Marrakech",
    country: "Morocco",
    tags: ["city", "culture", "market"],
  },
  {
    title: "Hiking the Inca Trail",
    place: "Machu Picchu",
    date: "2025-09-05",
    year: "2025",
    lat: -13.1631,
    lng: -72.545,
    color: "#2a9d8f",
    kind: "memory",
    image: "https://picsum.photos/seed/machupicchu/800/600",
    media: [
      "https://picsum.photos/seed/machu-1/800/600",
      "https://picsum.photos/seed/machu-2/800/600",
    ],
    favorite: false,
    description: "A memory from Machu Picchu, Peru.",
    note: null,
    symbol: "flag",
    city: "Machu Picchu",
    country: "Peru",
    tags: ["nature", "hiking", "adventure"],
  },
  {
    title: "Northern lights dance",
    place: "Reykjavik",
    date: "2025-12-28",
    year: "2025",
    lat: 64.1466,
    lng: -21.9426,
    color: "#6a4c93",
    kind: "memory",
    image: "https://picsum.photos/seed/aurora/800/600",
    media: ["https://picsum.photos/seed/iceland-1/800/600"],
    favorite: false,
    description: "A memory from Reykjavik, Iceland.",
    note: null,
    symbol: "star",
    city: "Reykjavik",
    country: "Iceland",
    tags: ["nature", "night", "aurora"],
  },
  {
    title: "Gondola ride at golden hour",
    place: "Venice",
    date: "2026-04-08",
    year: "2026",
    lat: 45.4408,
    lng: 12.3155,
    color: "#f4a261",
    kind: "memory",
    image: "https://picsum.photos/seed/venice-golden/800/600",
    media: [
      "https://picsum.photos/seed/venice-1/800/600",
      "https://picsum.photos/seed/venice-2/800/600",
    ],
    favorite: false,
    description: "A memory from Venice, Italy.",
    note: null,
    symbol: "heart",
    city: "Venice",
    country: "Italy",
    tags: ["romantic", "city", "water"],
  },
  {
    title: "Street food crawl",
    place: "Yaowarat Road, Bangkok",
    date: "2026-01-14",
    year: "2026",
    lat: 13.7399,
    lng: 100.5073,
    color: "#e9c46a",
    kind: "memory",
    image: "https://picsum.photos/seed/bangkok-food/800/600",
    media: [
      "https://picsum.photos/seed/bangkok-1/800/600",
      "https://picsum.photos/seed/bangkok-2/800/600",
      "https://picsum.photos/seed/bangkok-3/800/600",
    ],
    favorite: false,
    description: "A memory from Bangkok, Thailand.",
    note: null,
    symbol: "pin",
    city: "Bangkok",
    country: "Thailand",
    tags: ["food", "city", "night"],
  },
  {
    title: "Table Mountain hike",
    place: "Cape Town",
    date: "2025-10-12",
    year: "2025",
    lat: -33.9628,
    lng: 18.4098,
    color: "#2a9d8f",
    kind: "memory",
    image: "https://picsum.photos/seed/capetown/800/600",
    media: ["https://picsum.photos/seed/cape-1/800/600"],
    favorite: false,
    description: "A memory from Cape Town, South Africa.",
    note: null,
    symbol: "flag",
    city: "Cape Town",
    country: "South Africa",
    tags: ["nature", "hiking", "adventure"],
  },
  {
    title: "Sunset in Oia",
    place: "Santorini",
    date: "2026-06-22",
    year: "2026",
    lat: 36.4616,
    lng: 25.3753,
    color: "#ef766b",
    kind: "memory",
    image: "https://picsum.photos/seed/santorini-sunset/800/600",
    media: [
      "https://picsum.photos/seed/santorini-1/800/600",
      "https://picsum.photos/seed/santorini-2/800/600",
    ],
    favorite: true,
    description: "A memory from Santorini, Greece.",
    note: null,
    symbol: "heart",
    city: "Santorini",
    country: "Greece",
    tags: ["sunset", "romantic", "travel"],
  },
  {
    title: "Cherry blossom picnic",
    place: "Ueno Park, Tokyo",
    date: "2026-04-02",
    year: "2026",
    lat: 35.7148,
    lng: 139.773,
    color: "#ffb5c2",
    kind: "memory",
    image: "https://picsum.photos/seed/cherry-blossom/800/600",
    media: [
      "https://picsum.photos/seed/cherry-1/800/600",
      "https://picsum.photos/seed/cherry-2/800/600",
    ],
    favorite: false,
    description: "A memory from Tokyo, Japan.",
    note: null,
    symbol: "heart",
    city: "Tokyo",
    country: "Japan",
    tags: ["nature", "spring", "cherry-blossom"],
  },
  {
    title: "Surfing at Uluwatu",
    place: "Bali",
    date: "2025-08-17",
    year: "2025",
    lat: -8.8291,
    lng: 115.0849,
    color: "#264653",
    kind: "memory",
    image: "https://picsum.photos/seed/bali-surf/800/600",
    media: [
      "https://picsum.photos/seed/bali-1/800/600",
      "https://picsum.photos/seed/bali-2/800/600",
    ],
    favorite: false,
    description: "A memory from Bali, Indonesia.",
    note: null,
    symbol: "pin",
    city: "Bali",
    country: "Indonesia",
    tags: ["beach", "surf", "adventure"],
  },
  {
    title: "Night market in Taipei",
    place: "Shilin, Taipei",
    date: "2026-05-30",
    year: "2026",
    lat: 25.0898,
    lng: 121.5255,
    color: "#e76f51",
    kind: "memory",
    image: "https://picsum.photos/seed/taipei-night/800/600",
    media: [
      "https://picsum.photos/seed/taipei-1/800/600",
      "https://picsum.photos/seed/taipei-2/800/600",
    ],
    favorite: false,
    description: "A memory from Taipei, Taiwan.",
    note: null,
    symbol: "pin",
    city: "Taipei",
    country: "Taiwan",
    tags: ["food", "night", "city"],
  },
  {
    title: "Glacier lagoon kayaking",
    place: "Jökulsárlón, Iceland",
    date: "2025-12-30",
    year: "2025",
    lat: 64.0789,
    lng: -16.2386,
    color: "#457b9d",
    kind: "memory",
    image: "https://picsum.photos/seed/glacier-lagoon/800/600",
    media: ["https://picsum.photos/seed/glacier-1/800/600"],
    favorite: false,
    description: "A memory from Jökulsárlón, Iceland.",
    note: null,
    symbol: "star",
    city: "Jökulsárlón",
    country: "Iceland",
    tags: ["nature", "adventure", "ice"],
  },
  {
    title: "Wandering through lavender fields",
    place: "Provence",
    date: "2026-07-05",
    year: "2026",
    lat: 43.9493,
    lng: 5.1473,
    color: "#9b5de5",
    kind: "memory",
    image: "https://picsum.photos/seed/lavender/800/600",
    media: [
      "https://picsum.photos/seed/provence-1/800/600",
      "https://picsum.photos/seed/provence-2/800/600",
    ],
    favorite: false,
    description: "A memory from Provence, France.",
    note: null,
    symbol: "heart",
    city: "Provence",
    country: "France",
    tags: ["nature", "summer", "flowers"],
  },
  {
    title: "Riding the Trans-Siberian",
    place: "Trans-Siberian Railway",
    date: "2025-07-20",
    year: "2025",
    lat: 55.7558,
    lng: 37.6176,
    color: "#1d3557",
    kind: "memory",
    image: "https://picsum.photos/seed/transsiberian/800/600",
    media: [
      "https://picsum.photos/seed/train-1/800/600",
      "https://picsum.photos/seed/train-2/800/600",
    ],
    favorite: false,
    description: "A memory from Moscow → Vladivostok, Russia.",
    note: null,
    symbol: "diamond",
    city: "Moscow → Vladivostok",
    country: "Russia",
    tags: ["train", "adventure", "landscape"],
  },
];

export interface DemoThread {
  memoryIds: number[]; // indices into DEMO_MEMORIES
}

export const DEMO_THREADS: DemoThread[] = [
  { memoryIds: [0, 9] },     // Shibuya → Cherry blossom
  { memoryIds: [4, 12] },    // Iceland → Glacier lagoon
  { memoryIds: [1, 3, 7] },  // Bagan → Machu Picchu → Cape Town
  { memoryIds: [5, 8] },     // Venice → Santorini
];

/** Achievement IDs unlocked in the demo. */
export const DEMO_UNLOCKED_ACHIEVEMENTS: number[] = [1, 2, 3, 4, 5, 8, 10, 15, 20];
export const DEMO_UNLOCKED_MAP = new Set(DEMO_UNLOCKED_ACHIEVEMENTS);

export const DEMO_PROFILE = {
  id: "singleton",
  name: "Explorer",
  avatarPath: "https://picsum.photos/seed/avatar/200/200",
  locale: "en",
  knownTags: ["travel", "nature", "city", "night", "adventure", "food"],
  selectedTitle: "wanderer",
};
